In [19]:
class student:
    
    def __init__(self, age,name,roll,salary):
        self.age = age
        self.name=name
        self.roll=roll
        self.salary=salary
    
    def getage(self):
        print(self.age)
    def getname(self):
        print(self.name)
    def getroll(self):
        print(self.roll)
    def getsalary(self):
        print(self.salary)

In [20]:
s1 = student(10,"harshit", 101,1500000)

In [21]:
print(s1.age)

10


In [22]:
s1.age = 20

In [23]:
print(s1.age)

20


In [24]:
s1.getage()

20


In [25]:
s1.getname()

harshit


In [26]:
s1.getsalary()

1500000


In [27]:
s2 = student

In [28]:
s2 = s1   # Copying the object into other object

In [29]:
s2.age

20

In [30]:
s2.name

'harshit'

#### Inheritance in Python

In [53]:
class Vehicle():
    def __init__(self, cost, milege):
        self.cost = cost
        self.milege=milege
    def show_details(self):
        print(self.cost)
        print(self.milege)
        


In [54]:
v1=Vehicle(200,1000)

In [55]:
v1.cost

200

In [95]:
class Car(Vehicle):
    def __init__(self,cost, milege,model):
        super().__init__(cost,milege)
        self.model=model
        
    def car_show(self):
        print("This is sub class.")
        print("The model is {}".format(self.model))
        print(f"The cost is {self.cost}")
        print("The milege is ",self.milege)

In [96]:
c1=Car(100,10000,"audi")

In [97]:
c1.show_details()

100
10000


In [98]:
c1.car_show()

This is sub class.
The model is audi
The cost is 100
The milege is  10000


## Numpy

In [101]:
# Creating an array

import numpy as np

In [102]:
n1 = np.array([10,20,30,40,50])

In [103]:
n1

array([10, 20, 30, 40, 50])

In [106]:
type(n1)

numpy.ndarray

In [109]:
# Creating a 2D array

n2 = np.array([[1,2,3,4,5],[3,4,7,9,10],[12,23,34,56,68]])

In [110]:
type(n2)

numpy.ndarray

In [111]:
n2

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  7,  9, 10],
       [12, 23, 34, 56, 68]])

In [114]:
# Initialisation of numpy array
# Ususally we initialise the numpy array with 0s and then later we change.

# Syntax---->n3=np.zeros(rows,cols)
n3 = np.zeros((5,5))

In [115]:
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
n4= np.zeros((3,5))

In [117]:
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
# Full method--> To initialise the numpy array with  some number

n5 = np.full((2,4),10)


In [119]:
n5

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [120]:
# Initialise numpy array in a range
# Here the array is 1D

n6 = np.arange(10,20)

In [121]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [122]:
#three arguments then third one represents the gap
n7 = np.arange(10,100,10)

In [123]:
n7

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## Joining two numpy arrays
##### There are three ways of joining the numpy arrays -->

 1. vstack()
 2. hstack()
 3. column_stack()


In [130]:
# 1. vstack()--> It gives list of array by joining them row wise


n1 = np.array([1,2,3,4,5])
n2 = np.array([10,9,8,7,6])
np.vstack((n1,n2))

array([[ 1,  2,  3,  4,  5],
       [10,  9,  8,  7,  6]])

In [129]:
# 2. hstack()--> It joins by joining the two arrays in single line
# joins horizontally, one after the other

np.hstack((n1, n2))

array([ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6])

In [131]:
# 3. column_stack()--> It joins by making the column elements as 
# one row

np.column_stack((n1, n2))

array([[ 1, 10],
       [ 2,  9],
       [ 3,  8],
       [ 4,  7],
       [ 5,  6]])

## Intersection of two numpy arrays

In [132]:
# We have two arrays n1 and n2.
# We need to find the intersection of two arrsy 
# That is the common elements in the two arrays


In [135]:
n1 = np.array([1,2,3,7,5])
n2 = np.array([10,2,8,7,6])
np.intersect1d(n1, n2)

array([2, 7])

### n1-n2 elements

In [136]:
np.setdiff1d(n1, n2)

array([1, 3, 5])

In [138]:
np.setdiff1d(n2, n1)

array([ 6,  8, 10])

# Sum of two numpy Arrays

### 1. Sum of all elements in the two list

### 2. Sum of all elements row wise 
 Syntax --> np.sum([n1, n2], axis=1)
 
 ### 3. Sum of elements column wise
  Syntac --> np.sum([n1, n2], axis=0)

In [139]:
# np.sum([])--> Pass the two array in list inside sum function 
# 2. [It will return a single number that is the sum of all elements in the two arrays


np.sum([n1, n2])

51

In [140]:
# row wise

np.sum([n1, n2], axis =1)

array([18, 33])

In [141]:
np.sum([n1, n2], axis =0)

array([11,  4, 11, 14, 11])

In [142]:
## Arithmetic operations in numpy array

In [145]:
# Addition --> 1 is added to all elements of n1
n1 = n1+1

In [146]:
n1

array([3, 4, 5, 9, 7])

In [147]:
n1

array([3, 4, 5, 9, 7])

In [148]:
# subtraction
n1 = n1-1

In [149]:
n1

array([2, 3, 4, 8, 6])

In [151]:
n1= n1*2

In [152]:
n1

array([ 4,  6,  8, 16, 12])

## Saving the numpy array

In [153]:
np.save('myarr', n1)

## Loading the numpy array

In [155]:
n=np.load('myarr.npy')

In [156]:
n

array([ 4,  6,  8, 16, 12])